export enum LPCChestEnum {
  BROWN_PIRATE = 'BROWN_SHIRT',
  CHAIN_CHEST = 'CHAIN_CHEST',
  GOLD_CHEST = 'GOLD_CHEST',
  LEATHER_CHEST = 'LEATHER_CHEST',
  MAROON_PIRATE = 'MAROON_SHIRT',
  PLATE_CHEST = 'PLATE_CHEST',
  TEAL_PIRATE = 'TEAL_SHIRT',
  WHITE_PIRATE = 'WHITE_SHIRT'
}
