export enum LPCChestEnum {
  BROWN_SHIRT = 'BROWN_SHIRT',
  CHAIN_CHEST = 'CHAIN_CHEST',
  GOLD_CHEST = 'GOLD_CHEST',
  LEATHER_CHEST = 'LEATHER_CHEST',
  MAROON_SHIRT = 'MAROON_SHIRT',
  PLATE_CHEST = 'PLATE_CHEST',
  TEAL_SHIRT = 'TEAL_SHIRT',
  WHITE_SHIRT = 'WHITE_SHIRT'
}
