export enum LPCMaleChestEnum {
  BROWN_LONG_SLEEVE = 'BROWN_LONG_SLEEVE',
  CHAIN_CHEST = 'CHAIN_CHEST',
  GOLD_CHEST = 'GOLD_CHEST',
  LEATHER_CHEST = 'LEATHER_CHEST',
  MAROON_LONG_SLEEVE = 'MAROON_LONG_SLEEVE',
  PLATE_CHEST = 'PLATE_CHEST',
  TEAL_LONG_SLEEVE = 'TEAL_LONG_SLEEVE',
  WHITE_LONG_SLEEVE = 'WHITE_LONG_SLEEVE'
}

