export enum LPCFemaleHairEnum {
  BANGS_LONG = 'BANGS_LONG',
  BANGS_SHORT = 'BANGS_SHORT',
  LOOSE = 'LOOSE',
  PIXIE = 'PIXIE',
  PONY_TAIL = 'PONY_TAIL',
  PRINCESS = 'PRINCESS',
  SWOOP = 'SWOOP',
  UNKEMPT = 'UNKEMPT'
}
