export enum LPCFemaleChestEnum {
  BROWN_PIRATE = 'BROWN_PIRATE',
  CHAIN_CHEST = 'CHAIN_CHEST',
  GOLD_CHEST = 'GOLD_CHEST',
  LEATHER_CHEST = 'LEATHER_CHEST',
  MAROON_PIRATE = 'MAROON_PIRATE',
  PLATE_CHEST = 'PLATE_CHEST',
  TEAL_PIRATE = 'TEAL_PIRATE',
  WHITE_PIRATE = 'WHITE_PIRATE'
}

