export enum LPCHeadEnum {
  CHAIN_HOOD = 'CHAIN_HOOD',
  CHAIN_HAT = 'CHAIN_HAT',
  CLOTH_HOOD = 'CLOTH_HOOD',
  GOLDEN_HELM = 'GOLDEN_HELM',
  LEATHER_CAP = 'LEATHER_CAP',
  METAL_HELM = 'METAL_HELM',
  RED_BANDANNA = 'RED_BANDANNA'
}
