export enum LPCLegsEnum {
  GOLDEN_PANTS = 'GOLDEN_PANTS',
  MAGENTA_PANTS = 'MAGENTA_PANTS',
  METAL_PANTS = 'METAL_PANTS',
  RED_PANTS = 'RED_PANTS',
  TEAL_PANTS = 'TEAL_PANTS',
  WHITE_PANTS = 'WHITE_PANTS'
}

