package com.project.wow.dto.character.apperance;

public enum FemaleClothes {
    NO_CLOTHES,

    SLEEVLESS_SHIRT_BROWN,
    SLEEVLESS_SHIRT_TEAL,
    SLEEVLESS_SHIRT_MAROON,
    SLEEVLESS_SHIRT_WHITE,

    PIRATE_SHIRT_BROWN,
    PIRATE_SHIRT_TEAL,
    PIRATE_SHIRT_MAROON,
    PIRATE_SHIRT_WHITE,

    SLEEVLESS_TUNIC_BROWN,
    SLEEVLESS_TUNIC_TEAL,
    SLEEVLESS_TUNIC_MAROON,
    SLEEVLESS_TUNIC_WHITE,

    SARA_SHIRT,
    DRESS_WITH_SLASH,

    GOWN_UNDERDRESSED,
    GOWN_OVERSKIRT,
    GOWN_BLUE_VEST,

    ROBE_BLACK,
    ROBE_BLUE,
    ROBE_BROWN,
    ROBE_DARK_BROWN,
    ROBE_DARK_GRAY,
    ROBE_LIGHT_GRAY,
    ROBE_FORES_GREEN,
    ROBE_GREEN,
    ROBE_RED,
    ROBE_WHITE,

}
